In [1]:
## to compare individual video frames and see if there are any duplicates. 

import math
import csv 
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import path
import scipy as scipy
import scipy.io
import cv2

import os
os.listdir(os.getcwd())

import json as json
import pickle as pickle

import peaks


def error(img1, img2):
   diff = cv2.subtract(img1, img2)
   err = np.sum(diff**2)
   mse = err/(float(h*w))
   msre = np.sqrt(mse)
   return mse, diff


In [6]:
date = '20230512'

raw_path = "E:/bruker_vid_2023/" + str(date) + "/analysis/"  ##JPEGS AND ROIS MUST BE SAVED IN SEPERATE ANALYSIS FOLDER

for fly_dir in os.listdir(raw_path):
    dir_number = peaks.find_number(peaks.find_fly_string(fly_dir), dash = 'y')
    #print('fly dir number:', dir_number)
    if len(dir_number) == 0:
        raise Exception(f"ERROR: THERE IS NO DIRECTORY NUMBER FOR...{fly_dir}")
    if '.zip' not in fly_dir and '.txt' not in fly_dir and 'Roi' not in fly_dir:
        print('fly dir:', fly_dir)
        jpeg_path = os.path.join(raw_path, fly_dir)
        print('jpeg path', jpeg_path)

        if os.path.exists(jpeg_path):
            jpeg_file_names = os.listdir(jpeg_path)
            sorted_jpeg_file_names = sorted(jpeg_file_names)
            ##just verification that sorting process works ok
            print('sorted', sorted_jpeg_file_names[0:5])

            ## actual testing to see if one frame and the next are identical
            for i in range(len(sorted_jpeg_file_names)-1):
            first_frame = os.path.join(jpeg_path, sorted_jpeg_file_names[i])
            second_frame = os.path.join(jpeg_path, sorted_jpeg_file_names[i+1])
            img1 = cv2.imread(first_frame)
            img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
            h, w = img1.shape
            img2 = cv2.imread(second_frame)
            img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

            match_error12, diff12 = error(img1, img2)
            if match_error12 < 0.1:
                print(f'frame {first_frame} and frame {second_frame} match')
                print(f'error value = {match_error12}')  #if identical this will be == 0

fly dir number: 1
fly dir: fly1
jpeg path E:/bruker_vid_2023/20230512/analysis/fly1
sorted ['V01-frame_0000001.jpg', 'V01-frame_0000002.jpg', 'V01-frame_0000003.jpg', 'V01-frame_0000004.jpg', 'V01-frame_0000005.jpg']
fly dir number: 2
fly dir: fly2
jpeg path E:/bruker_vid_2023/20230512/analysis/fly2
sorted ['V02-frame_0000001.jpg', 'V02-frame_0000002.jpg', 'V02-frame_0000003.jpg', 'V02-frame_0000004.jpg', 'V02-frame_0000005.jpg']
fly dir number: 2
fly dir number: 1
fly dir number: 1
fly dir number: 2
fly dir number: 2


In [19]:
jpeg_name_set = sorted_jpeg_file_names[0:5]
print(type(jpeg_name_set))
print(jpeg_name_set[3])
jpeg_name_set.insert(3, jpeg_name_set[3])
print(jpeg_name_set)
print(len(jpeg_name_set))

<class 'list'>
V02-frame_0000004.jpg
['V02-frame_0000001.jpg', 'V02-frame_0000002.jpg', 'V02-frame_0000003.jpg', 'V02-frame_0000004.jpg', 'V02-frame_0000004.jpg', 'V02-frame_0000005.jpg']
6


In [25]:
jpeg_name_set = sorted_jpeg_file_names[0:5]
print(type(jpeg_name_set))
print(jpeg_name_set[3])
jpeg_name_set.insert(3, jpeg_name_set[3])
print(jpeg_name_set)
print(len(jpeg_name_set))

frame_file_0 = os.path.join(jpeg_path, jpeg_name_set[0])
frame_file_1 = os.path.join(jpeg_path, jpeg_name_set[1])
frame_file_2 = os.path.join(jpeg_path, jpeg_name_set[2])


img1 = cv2.imread(frame_file_0)
img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
print(img1.shape)
h, w = img1.shape

img2 = cv2.imread(frame_file_1)
img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
img3 = cv2.imread(frame_file_2)
img3 = cv2.cvtColor(img3, cv2.COLOR_BGR2GRAY)

def error(img1, img2):
   diff = cv2.subtract(img1, img2)
   err = np.sum(diff**2)
   mse = err/(float(h*w))
   msre = np.sqrt(mse)
   return mse, diff

match_error12, diff12 = error(img1, img2)
match_error13, diff13 = error(img1, img3)
match_error23, diff23 = error(img2, img3)

# print(match_error12)
# print(match_error13)
# print(match_error23)

##this is a test to make sure it will find identical frames
for i in range(len(jpeg_name_set)-1):
   first_frame = os.path.join(jpeg_path, jpeg_name_set[i])
   second_frame = os.path.join(jpeg_path, jpeg_name_set[i+1])
   img1 = cv2.imread(first_frame)
   img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
   h, w = img1.shape
   img2 = cv2.imread(second_frame)
   img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

   match_error12, diff12 = error(img1, img2)
   if match_error12 < 0.1:
      print(f'FOR THE TEST! frame {first_frame} and frame {second_frame} match')
      print(match_error12)


## actual testing
for i in range(len(sorted_jpeg_file_names)-1):
   first_frame = os.path.join(jpeg_path, sorted_jpeg_file_names[i])
   second_frame = os.path.join(jpeg_path, sorted_jpeg_file_names[i+1])
   img1 = cv2.imread(first_frame)
   img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
   h, w = img1.shape
   img2 = cv2.imread(second_frame)
   img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

   match_error12, diff12 = error(img1, img2)
   if match_error12 < 0.1:
      print(f'frame {first_frame} and frame {second_frame} match')
      print(match_error12)
   

<class 'list'>
V02-frame_0000004.jpg
['V02-frame_0000001.jpg', 'V02-frame_0000002.jpg', 'V02-frame_0000003.jpg', 'V02-frame_0000004.jpg', 'V02-frame_0000004.jpg', 'V02-frame_0000005.jpg']
6
(1080, 1440)
FOR THE TEST! frame E:/bruker_vid_2023/20230512/analysis/fly2\V02-frame_0000004.jpg and frame E:/bruker_vid_2023/20230512/analysis/fly2\V02-frame_0000004.jpg match
0.0


In [54]:
## choose 10 points at random in image
##get a matrix of 10 points x frames
## do a subtraction np.diff between adjacent frames
## sum over the pixels and see if they are zero for a diff

jpeg_name_set = sorted_jpeg_file_names[0:5]
print(type(jpeg_name_set))
print(jpeg_name_set[3])
jpeg_name_set.insert(3, jpeg_name_set[3])
print(jpeg_name_set)
print(len(jpeg_name_set))

frame_file_0 = os.path.join(jpeg_path, jpeg_name_set[0])
frame_file_1 = os.path.join(jpeg_path, jpeg_name_set[1])
frame_file_2 = os.path.join(jpeg_path, jpeg_name_set[2])


img1 = cv2.imread(frame_file_0)
img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
print(img1.shape)
x, y = img1.shape

img2 = cv2.imread(frame_file_1)
img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
img3 = cv2.imread(frame_file_2)
img3 = cv2.cvtColor(img3, cv2.COLOR_BGR2GRAY)

print(np.shape(img1))
print(img3[47][47])

print(np.max(img3))
print(np.min(img3))

number_of_pixels = 10

random_x = np.random.randint(0,x, size = number_of_pixels)
random_y = np.random.randint(0,y, size = number_of_pixels)
pts_1 = img1[random_x, random_y]
pts_2 = img2[random_x, random_y]
pts_3 = img3[random_x, random_y]
print(pts_1)
print(pts_2)

matrix = np.array([pts_1, pts_2, pts_3])

print(matrix)
print(np.shape(matrix))
print(np.diff(matrix, axis = 0))

all_pts = []
random_x = np.random.randint(0,x, size = number_of_pixels)
random_y = np.random.randint(0,y, size = number_of_pixels)
for i in range(len(jpeg_name_set)):
    first_frame = os.path.join(jpeg_path, jpeg_name_set[i])
    #second_frame = os.path.join(jpeg_path, jpeg_name_set[i+1])
    img1 = cv2.imread(first_frame)
    img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
    x, y = img1.shape
    # img2 = cv2.imread(second_frame)
    # img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

    ##get random pixels
    pts = img1[random_x, random_y]
    #pts_2 = img2[random_x, random_y]
    all_pts.append(pts)

print(np.shape(all_pts))
pts_diff = np.diff(all_pts, axis = 0)

print(np.shape(pts_diff))
sum = np.sum(pts_diff, axis = 1)
print(np.where(sum == 0))
print(jpeg_name_set)


    

<class 'list'>
V01-frame_0000004.jpg
['V01-frame_0000001.jpg', 'V01-frame_0000002.jpg', 'V01-frame_0000003.jpg', 'V01-frame_0000004.jpg', 'V01-frame_0000004.jpg', 'V01-frame_0000005.jpg']
6
(1080, 1440)
(1080, 1440)
6
255
0
[ 4  4  4 35  3  3  3  6  2  3]
[ 3  3  3 33  3  3  3  6  3  3]
[[ 4  4  4 35  3  3  3  6  2  3]
 [ 3  3  3 33  3  3  3  6  3  3]
 [ 3  3  4 33  5  3  3  6  3  4]]
(3, 10)
[[255 255 255 254   0   0   0   0   1   0]
 [  0   0   1   0   2   0   0   0   0   1]]
(6, 10)
(5, 10)
(array([3], dtype=int64),)
['V01-frame_0000001.jpg', 'V01-frame_0000002.jpg', 'V01-frame_0000003.jpg', 'V01-frame_0000004.jpg', 'V01-frame_0000004.jpg', 'V01-frame_0000005.jpg']


In [55]:
##choosing random pixels to compare
##if the same frame then the difference for that frame == 0 all the way across

number_of_pixels = 10
all_pts = []
random_x = np.random.randint(0,x, size = number_of_pixels)
random_y = np.random.randint(0,y, size = number_of_pixels)
for i in range(len(sorted_jpeg_file_names)):
    first_frame = os.path.join(jpeg_path, sorted_jpeg_file_names[i])
    img1 = cv2.imread(first_frame)
    img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
    x, y = img1.shape

    ##get random pixels
    pts = img1[random_x, random_y]
    all_pts.append(pts)

print(np.shape(all_pts))
print(np.shape(all_pts))
pts_diff = np.diff(all_pts, axis = 0)

print(np.shape(pts_diff))
sum = np.sum(pts_diff, axis = 1)
print(np.where(sum == 0))


(93217, 10)
(93217, 10)
(93216, 10)
(array([   18,    56,    79, ..., 93120, 93165, 93167], dtype=int64),)


In [59]:
zeros = np.where(sum == 0)[0]
print(len(zeros))
print(len(sum))

##check the zeros frames to see if they are still zeros with new pixels 
# need to check the next frame to compare
number_of_pixels = 30
all_pts = []
all_diff = []
random_x = np.random.randint(0,x, size = number_of_pixels)
random_y = np.random.randint(0,y, size = number_of_pixels)
for i in zeros:
    first_frame = os.path.join(jpeg_path, sorted_jpeg_file_names[i])
    next_frame = os.path.join(jpeg_path, sorted_jpeg_file_names[i + 1])
    img1 = cv2.imread(first_frame)
    img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
    img2 = cv2.imread(next_frame)
    img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
    x, y = img1.shape

    ##get random pixels
    pts1 = img1[random_x, random_y]
    pts2 = img2[random_x, random_y]
    all_pts.append(pts1)
    all_pts.append(pts2)
    diff = pts1 - pts2
    all_diff.append(diff)

1864
93216


In [28]:
jpeg_path = os.path.join(raw_path, 'fly1')
print('jpeg path', jpeg_path)

jpeg_file_names = os.listdir(jpeg_path)
sorted_jpeg_file_names = sorted(jpeg_file_names)

## actual testing
for i in range(len(sorted_jpeg_file_names)-1):
   first_frame = os.path.join(jpeg_path, sorted_jpeg_file_names[i])
   second_frame = os.path.join(jpeg_path, sorted_jpeg_file_names[i+1])
   img1 = cv2.imread(first_frame)
   img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
   h, w = img1.shape
   img2 = cv2.imread(second_frame)
   img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

   match_error12, diff12 = error(img1, img2)
   if match_error12 < 0.1:
      print(f'frame {first_frame} and frame {second_frame} match')
      print(match_error12)

jpeg path E:/bruker_vid_2023/20230512/analysis/fly1


KeyboardInterrupt: 